// Code generated by goyacc - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import (
	"github.com/potix2/goscheme/ast"
	"strconv"
)

type yySymType struct {
	yys   int
	exprs []ast.Expr
	expr  ast.Expr
	tok   Token
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57349
	yyEofCode = 57344
	BOOLEAN   = 57348
	IDENT     = 57346
	NUMBER    = 57347
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -30
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		40:    0,  // '(' (31x)
		57348: 1,  // BOOLEAN (31x)
		57346: 2,  // IDENT (31x)
		57347: 3,  // NUMBER (31x)
		41:    4,  // ')' (30x)
		39:    5,  // '\'' (27x)
		57344: 6,  // $end (26x)
		46:    7,  // '.' (15x)
		57350: 8,  // bool (9x)
		57357: 9,  // identifier (9x)
		57358: 10, // number (9x)
		57356: 11, // expr (5x)
		57360: 12, // proc_call (5x)
		57362: 13, // quotation (5x)
		57363: 14, // self_evaluating (5x)
		57353: 15, // compound_datum (4x)
		57355: 16, // datum (4x)
		57364: 17, // simple_datum (4x)
		57365: 18, // symbol (4x)
		57351: 19, // command (2x)
		57352: 20, // commands (2x)
		57354: 21, // data (2x)
		57359: 22, // operands (2x)
		57361: 23, // program (1x)
		57349: 24, // $default (0x)
		57345: 25, // error (0x)
	}

	yySymNames = []string{
		"'('",
		"BOOLEAN",
		"IDENT",
		"NUMBER",
		"')'",
		"'\\''",
		"$end",
		"'.'",
		"bool",
		"identifier",
		"number",
		"expr",
		"proc_call",
		"quotation",
		"self_evaluating",
		"compound_datum",
		"datum",
		"simple_datum",
		"symbol",
		"command",
		"commands",
		"data",
		"operands",
		"program",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {23, 1},
		2:  {20, 1},
		3:  {20, 2},
		4:  {19, 1},
		5:  {11, 1},
		6:  {11, 1},
		7:  {11, 1},
		8:  {11, 1},
		9:  {14, 1},
		10: {14, 1},
		11: {13, 2},
		12: {16, 1},
		13: {16, 1},
		14: {17, 1},
		15: {17, 1},
		16: {17, 1},
		17: {15, 2},
		18: {15, 3},
		19: {15, 5},
		20: {21, 1},
		21: {21, 2},
		22: {18, 1},
		23: {9, 1},
		24: {8, 1},
		25: {10, 1},
		26: {12, 3},
		27: {12, 4},
		28: {22, 1},
		29: {22, 2},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [39][]uint8{
		// 0
		{45, 43, 42, 44, 5: 41, 8: 39, 37, 40, 34, 38, 35, 36, 19: 33, 32, 23: 31},
		{6: 30},
		{6: 29},
		{45, 43, 42, 44, 5: 41, 28, 8: 39, 37, 40, 34, 38, 35, 36, 19: 33, 68},
		{26, 26, 26, 26, 5: 26, 26},
		// 5
		{25, 25, 25, 25, 25, 25, 25},
		{24, 24, 24, 24, 24, 24, 24},
		{23, 23, 23, 23, 23, 23, 23},
		{22, 22, 22, 22, 22, 22, 22},
		{21, 21, 21, 21, 21, 21, 21},
		// 10
		{20, 20, 20, 20, 20, 20, 20},
		{58, 43, 42, 44, 8: 55, 59, 56, 15: 54, 52, 53, 57},
		{7, 7, 7, 7, 7, 7, 7, 7},
		{6, 6, 6, 6, 6, 6, 6, 6},
		{5, 5, 5, 5, 5, 5, 5, 5},
		// 15
		{45, 43, 42, 44, 5: 41, 8: 39, 37, 40, 46, 38, 35, 36},
		{45, 43, 42, 44, 47, 41, 8: 39, 37, 40, 49, 38, 35, 36, 22: 48},
		{4, 4, 4, 4, 4, 4, 4},
		{4: 51},
		{45, 43, 42, 44, 2, 41, 8: 39, 37, 40, 49, 38, 35, 36, 22: 50},
		// 20
		{4: 1},
		{3, 3, 3, 3, 3, 3, 3},
		{19, 19, 19, 19, 19, 19, 19},
		{18, 18, 18, 18, 18, 18, 18, 18},
		{17, 17, 17, 17, 17, 17, 17, 17},
		// 25
		{16, 16, 16, 16, 16, 16, 16, 16},
		{15, 15, 15, 15, 15, 15, 15, 15},
		{14, 14, 14, 14, 14, 14, 14, 14},
		{58, 43, 42, 44, 60, 8: 55, 59, 56, 15: 54, 62, 53, 57, 21: 61},
		{8, 8, 8, 8, 8, 8, 8, 8},
		// 30
		{13, 13, 13, 13, 13, 13, 13, 13},
		{4: 64, 7: 65},
		{58, 43, 42, 44, 10, 7: 10, 55, 59, 56, 15: 54, 62, 53, 57, 21: 63},
		{4: 9, 7: 9},
		{12, 12, 12, 12, 12, 12, 12, 12},
		// 35
		{58, 43, 42, 44, 8: 55, 59, 56, 15: 54, 66, 53, 57},
		{4: 67},
		{11, 11, 11, 11, 11, 11, 11, 11},
		{6: 27},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 25

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.exprs = yyS[yypt-0].exprs
			if l, ok := yylex.(*Lexer); ok {
				l.exprs = yyVAL.exprs
			}
		}
	case 2:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-0].expr})
		}
	case 3:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}
	case 11:
		{
			yyVAL.expr = ast.QuoteExpr{yyS[yypt-0].expr}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 17:
		{
			yyVAL.expr = ast.MakeListFromSlice([]ast.Expr{})
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 18:
		{
			yyVAL.expr = ast.MakeListFromSlice(yyS[yypt-1].exprs)
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 19:
		{
			p := ast.MakeListFromSlice(yyS[yypt-3].exprs)
			p.Cdr = yyS[yypt-1].expr
			yyVAL.expr = p
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 20:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-0].expr})
		}
	case 21:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}
	case 23:
		{
			yyVAL.expr = ast.IdentExpr{Lit: yyS[yypt-0].tok.Lit}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 24:
		{
			lit, _ := strconv.ParseBool(yyS[yypt-0].tok.Lit)
			yyVAL.expr = ast.BooleanExpr{Lit: lit}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 25:
		{
			yyVAL.expr = ast.StringToNumber(yyS[yypt-0].tok.Lit)
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 26:
		{
			yyVAL.expr = ast.AppExpr{Exprs: []ast.Expr{yyS[yypt-1].expr}}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 27:
		{
			yyVAL.expr = ast.AppExpr{Exprs: append([]ast.Expr{yyS[yypt-2].expr}, yyS[yypt-1].exprs...)}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 28:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-0].expr})
		}
	case 29:
		{
			yyVAL.exprs = append([]ast.Expr{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
