// Code generated by goyacc - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import (
	"github.com/potix2/goscheme/scm"
	"strconv"
)

type yySymType struct {
	yys   int
	exprs []scm.Object
	expr  scm.Object
	tok   Token
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57350
	yyEofCode = 57344
	BOOLEAN   = 57348
	IDENT     = 57346
	NUMBER    = 57347
	STRING    = 57349
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -32
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		40:    0,  // '(' (33x)
		57348: 1,  // BOOLEAN (33x)
		57346: 2,  // IDENT (33x)
		57347: 3,  // NUMBER (33x)
		41:    4,  // ')' (32x)
		39:    5,  // '\'' (29x)
		57349: 6,  // STRING (29x)
		57344: 7,  // $end (28x)
		46:    8,  // '.' (15x)
		57351: 9,  // bool (9x)
		57358: 10, // identifier (9x)
		57359: 11, // number (9x)
		57357: 12, // expr (5x)
		57361: 13, // proc_call (5x)
		57363: 14, // quotation (5x)
		57364: 15, // self_evaluating (5x)
		57366: 16, // string (5x)
		57354: 17, // compound_datum (4x)
		57356: 18, // datum (4x)
		57365: 19, // simple_datum (4x)
		57367: 20, // symbol (4x)
		57352: 21, // command (2x)
		57353: 22, // commands (2x)
		57355: 23, // data (2x)
		57360: 24, // operands (2x)
		57362: 25, // program (1x)
		57350: 26, // $default (0x)
		57345: 27, // error (0x)
	}

	yySymNames = []string{
		"'('",
		"BOOLEAN",
		"IDENT",
		"NUMBER",
		"')'",
		"'\\''",
		"STRING",
		"$end",
		"'.'",
		"bool",
		"identifier",
		"number",
		"expr",
		"proc_call",
		"quotation",
		"self_evaluating",
		"string",
		"compound_datum",
		"datum",
		"simple_datum",
		"symbol",
		"command",
		"commands",
		"data",
		"operands",
		"program",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {25, 1},
		2:  {22, 1},
		3:  {22, 2},
		4:  {21, 1},
		5:  {12, 1},
		6:  {12, 1},
		7:  {12, 1},
		8:  {12, 1},
		9:  {15, 1},
		10: {15, 1},
		11: {15, 1},
		12: {14, 2},
		13: {18, 1},
		14: {18, 1},
		15: {19, 1},
		16: {19, 1},
		17: {19, 1},
		18: {17, 2},
		19: {17, 3},
		20: {17, 5},
		21: {23, 1},
		22: {23, 2},
		23: {20, 1},
		24: {10, 1},
		25: {9, 1},
		26: {11, 1},
		27: {16, 1},
		28: {13, 3},
		29: {13, 4},
		30: {24, 1},
		31: {24, 2},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [41][]uint8{
		// 0
		{49, 46, 45, 47, 5: 44, 48, 9: 41, 39, 42, 36, 40, 37, 38, 43, 21: 35, 34, 25: 33},
		{7: 32},
		{7: 31},
		{49, 46, 45, 47, 5: 44, 48, 30, 9: 41, 39, 42, 36, 40, 37, 38, 43, 21: 35, 72},
		{28, 28, 28, 28, 5: 28, 28, 28},
		// 5
		{27, 27, 27, 27, 27, 27, 27, 27},
		{26, 26, 26, 26, 26, 26, 26, 26},
		{25, 25, 25, 25, 25, 25, 25, 25},
		{24, 24, 24, 24, 24, 24, 24, 24},
		{23, 23, 23, 23, 23, 23, 23, 23},
		// 10
		{22, 22, 22, 22, 22, 22, 22, 22},
		{21, 21, 21, 21, 21, 21, 21, 21},
		{62, 46, 45, 47, 9: 59, 63, 60, 17: 58, 56, 57, 61},
		{8, 8, 8, 8, 8, 8, 8, 8, 8},
		{7, 7, 7, 7, 7, 7, 7, 7, 7},
		// 15
		{6, 6, 6, 6, 6, 6, 6, 6, 6},
		{5, 5, 5, 5, 5, 5, 5, 5},
		{49, 46, 45, 47, 5: 44, 48, 9: 41, 39, 42, 50, 40, 37, 38, 43},
		{49, 46, 45, 47, 51, 44, 48, 9: 41, 39, 42, 53, 40, 37, 38, 43, 24: 52},
		{4, 4, 4, 4, 4, 4, 4, 4},
		// 20
		{4: 55},
		{49, 46, 45, 47, 2, 44, 48, 9: 41, 39, 42, 53, 40, 37, 38, 43, 24: 54},
		{4: 1},
		{3, 3, 3, 3, 3, 3, 3, 3},
		{20, 20, 20, 20, 20, 20, 20, 20},
		// 25
		{19, 19, 19, 19, 19, 19, 19, 19, 19},
		{18, 18, 18, 18, 18, 18, 18, 18, 18},
		{17, 17, 17, 17, 17, 17, 17, 17, 17},
		{16, 16, 16, 16, 16, 16, 16, 16, 16},
		{15, 15, 15, 15, 15, 15, 15, 15, 15},
		// 30
		{62, 46, 45, 47, 64, 9: 59, 63, 60, 17: 58, 66, 57, 61, 23: 65},
		{9, 9, 9, 9, 9, 9, 9, 9, 9},
		{14, 14, 14, 14, 14, 14, 14, 14, 14},
		{4: 68, 8: 69},
		{62, 46, 45, 47, 11, 8: 11, 59, 63, 60, 17: 58, 66, 57, 61, 23: 67},
		// 35
		{4: 10, 8: 10},
		{13, 13, 13, 13, 13, 13, 13, 13, 13},
		{62, 46, 45, 47, 9: 59, 63, 60, 17: 58, 70, 57, 61},
		{4: 71},
		{12, 12, 12, 12, 12, 12, 12, 12, 12},
		// 40
		{7: 29},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 27

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yyVAL.exprs = yyS[yypt-0].exprs
			if l, ok := yylex.(*Lexer); ok {
				l.exprs = yyVAL.exprs
			}
		}
	case 2:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-0].expr})
		}
	case 3:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}
	case 12:
		{
			yyVAL.expr = scm.Quote{yyS[yypt-0].expr}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 18:
		{
			yyVAL.expr = scm.MakeListFromSlice([]scm.Object{})
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 19:
		{
			yyVAL.expr = scm.MakeListFromSlice(yyS[yypt-1].exprs)
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 20:
		{
			p := scm.MakeListFromSlice(yyS[yypt-3].exprs)
			p.Cdr = yyS[yypt-1].expr
			yyVAL.expr = p
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 21:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-0].expr})
		}
	case 22:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}
	case 24:
		{
			yyVAL.expr = scm.Symbol{Lit: yyS[yypt-0].tok.Lit}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 25:
		{
			lit, _ := strconv.ParseBool(yyS[yypt-0].tok.Lit)
			yyVAL.expr = scm.Boolean{Lit: lit}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 26:
		{
			yyVAL.expr = scm.StringToNumber(yyS[yypt-0].tok.Lit)
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 27:
		{
			yyVAL.expr = scm.String(yyS[yypt-0].tok.Lit)
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 28:
		{
			yyVAL.expr = scm.Subp{Objs: []scm.Object{yyS[yypt-1].expr}}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 29:
		{
			yyVAL.expr = scm.Subp{Objs: append([]scm.Object{yyS[yypt-2].expr}, yyS[yypt-1].exprs...)}
			if l, ok := yylex.(*Lexer); ok {
				l.expr = yyVAL.expr
			}
		}
	case 30:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-0].expr})
		}
	case 31:
		{
			yyVAL.exprs = append([]scm.Object{yyS[yypt-1].expr}, yyS[yypt-0].exprs...)
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
